### ISSUE TITLE
A bunch of VS Errors: Can't Run OOB

### ISSUE THREAD

**Issue by mzhukovs** [Dev-Squared/VuetifyDotnetCore2Sample#1]
Please help. Would really love to get started with this but can't seem to find a working template to get going in VS2017 w/ core2 Vue and TypeScript. thank you.

Many errors including Error TS2709 (TS) Cannot use namespace 'Vue' as a type.	VuetifyDotnetCore2Sample-master (tsconfig project)	C:\Repos\VuetifyDotnetCore2Sample-master\node_modules\vue-router\types\router.d.ts

ERROR in [at-loader] ./ClientApp/components/app/app.ts:4:2 
    TS2345: Argument of type 'typeof AppComponent' is not assignable to parameter of type 'VueClass'.
  Type 'typeof AppComponent' is not assignable to type 'new () => Vue'.
    Type 'AppComponent' is not assignable to type 'Vue'.
      Property '$el' is missing in type 'AppComponent'.
ERROR in [at-loader] ./ClientApp/components/app/app.ts:9:43 
    TS2509: Base constructor return type 'CombinedVueInstance<Vue, Data, Methods, Computed, Record<PropNames, any>>' is not a class or interface type.
ERROR in [at-loader] ./ClientApp/components/counter/counter.ts:4:1 
    TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type '<V extends VueClass>(target: V) => V' is not assignable to type 'typeof CounterComponent'.
    Property 'extend' is missing in type '<V extends VueClass>(target: V) => V'.
ERROR in [at-loader] ./ClientApp/components/counter/counter.ts:5:47 
    TS2509: Base constructor return type 'CombinedVueInstance<Vue, Data, Methods, Computed, Record<PropNames, any>>' is not a class or interface type.
ERROR in [at-loader] ./ClientApp/components/fetchdata/fetchdata.ts:11:1 
    TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type '<V extends VueClass>(target: V) => V' is not assignable to type 'typeof FetchDataComponent'.
    Property 'extend' is missing in type '<V extends VueClass>(target: V) => V'.
ERROR in [at-loader] ./ClientApp/components/fetchdata/fetchdata.ts:12:49 
    TS2509: Base constructor return type 'CombinedVueInstance<Vue, Data, Methods, Computed, Record<PropNames, any>>' is not a class or interface type.
ERROR in [at-loader] ./node_modules/vue-router/types/router.d.ts:4:35 
    TS2304: Cannot find name 'Vue'.
ERROR in [at-loader] ./node_modules/vue-router/types/router.d.ts:13:43 
    TS2304: Cannot find name 'Vue'.
ERROR in [at-loader] ./node_modules/vue-router/types/router.d.ts:19:8 
    TS2304: Cannot find name 'Vue'.
ERROR in [at-loader] ./node_modules/vue-router/types/router.d.ts:92:25 
    TS2304: Cannot find name 'Vue'.
ERROR in [at-loader] ./node_modules/vue-router/types/vue.d.ts:17:13 
    TS2428: All declarations of 'ComponentOptions' must have identical type parameters.
ERROR in [at-loader] ./node_modules/vue-router/types/vue.d.ts:17:40 
    TS2304: Cannot find name 'Vue'.
ERROR in [at-loader] ./node_modules/vue/types/options.d.ts:53:18 
    TS2428: All declarations of 'ComponentOptions' must have identical type parameters.

**Comment by johnkuefler** [comment]
I don't have any issues running OOB. I just pulled it down on a new computer and it ran fine. Do you have the latest version of nodejs installed? Visual Studio 2017 should take care of restoring your npm packages but if not you may have to run `npm install` from the project directory.  
  
I'm running VS 2017 version 15.5.6 with the ASP.NET and web development, and .NET Core cross-platform development workloads installed.

**Comment by mzhukovs** [comment]
@johnkuefler i appreciate the response. Issue was related to this: https://github.com/vuejs/vue-class-component/issues/181

I had latest typescript sdk but template came with NOT the latest version of vue. So simply updating it via npm solved the issue...

**Comment by mzhukovs** [comment]
Fyi @johnkuefler also had to remove require keyword from the import statements for Vue in router.d.ts and vue.d.ts  

I have one more likely very dumb question if you would be so kind - why are the extensions .vue.html instead of .vue?

**Comment by johnkuefler** [comment]
This template is based on the Microsoft Vue SPA Vue template, and they had the vue files in there that way for some reason. We wanted to add vuetify with as few modifications to the original template as possible, so we left it that way. You could probably switch them to .vue without any issues. If you feel that you've been able to improve the template, feel free to submit a Pull Request and we  might look at merging your updates in.
